// This file is generated by Sapper — do not edit it!
// webpack does not support export * as root_comp yet so do a two line import/export
import * as root_comp from '../../src/routes/_layout.svelte';
export { root_comp };
export { default as ErrorComponent } from '../../src/routes/_error.svelte';

export const ignore = [];

export const components = [
	{
		js: () => import(/* webpackChunkName: "index" */ "../../src/routes/index.svelte")
	},
	{
		js: () => import(/* webpackChunkName: "about" */ "../../src/routes/about.svelte")
	}
];

export const routes = [
	{
		// index.svelte
		pattern: /^\/$/,
		parts: [
			{ i: 0 }
		]
	},

	{
		// about.svelte
		pattern: /^\/about\/?$/,
		parts: [
			{ i: 1 }
		]
	}
];