// This file is generated by Sapper — do not edit it!
import * as component_0 from "../../src/routes/index.svelte";
import * as component_1 from "../../src/routes/about.svelte";
import * as root_comp from "../../src/routes/_layout.svelte";
import error from "../../src/routes/_error.svelte";

const d = decodeURIComponent;

export const manifest = {
	server_routes: [
		
	],

	pages: [
		{
			// index.svelte
			pattern: /^\/$/,
			parts: [
				{ name: "index", file: "index.svelte", component: component_0 }
			]
		},

		{
			// about.svelte
			pattern: /^\/about\/?$/,
			parts: [
				{ name: "about", file: "about.svelte", component: component_1 }
			]
		}
	],

	root_comp,
	error
};

export const build_dir = "__sapper__/build";

export const src_dir = "src";

export const dev = false;